/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivateRouteImport } from './routes/_private'
import { Route as GuestRouteImport } from './routes/_guest'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicCartRouteImport } from './routes/_public/cart'
import { Route as PrivateAccountRouteImport } from './routes/_private/account'
import { Route as GuestResetPasswordRouteImport } from './routes/_guest/reset-password'
import { Route as GuestRegisterRouteImport } from './routes/_guest/register'
import { Route as GuestLoginRouteImport } from './routes/_guest/login'
import { Route as GuestConfirmEmailRouteImport } from './routes/_guest/confirm-email'
import { Route as PublicGalleryIndexRouteImport } from './routes/_public/gallery/index'
import { Route as PublicGalleryIdRouteImport } from './routes/_public/gallery/$id'
import { Route as PublicEditorIdRouteImport } from './routes/_public/editor.$id'

const PrivateRoute = PrivateRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRoute = GuestRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/_public/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicCartRoute = PublicCartRouteImport.update({
  id: '/_public/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateAccountRoute = PrivateAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => PrivateRoute,
} as any)
const GuestResetPasswordRoute = GuestResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => GuestRoute,
} as any)
const GuestRegisterRoute = GuestRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => GuestRoute,
} as any)
const GuestLoginRoute = GuestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestRoute,
} as any)
const GuestConfirmEmailRoute = GuestConfirmEmailRouteImport.update({
  id: '/confirm-email',
  path: '/confirm-email',
  getParentRoute: () => GuestRoute,
} as any)
const PublicGalleryIndexRoute = PublicGalleryIndexRouteImport.update({
  id: '/_public/gallery/',
  path: '/gallery/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicGalleryIdRoute = PublicGalleryIdRouteImport.update({
  id: '/_public/gallery/$id',
  path: '/gallery/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicEditorIdRoute = PublicEditorIdRouteImport.update({
  id: '/_public/editor/$id',
  path: '/editor/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/confirm-email': typeof GuestConfirmEmailRoute
  '/login': typeof GuestLoginRoute
  '/register': typeof GuestRegisterRoute
  '/reset-password': typeof GuestResetPasswordRoute
  '/account': typeof PrivateAccountRoute
  '/cart': typeof PublicCartRoute
  '/': typeof PublicIndexRoute
  '/editor/$id': typeof PublicEditorIdRoute
  '/gallery/$id': typeof PublicGalleryIdRoute
  '/gallery': typeof PublicGalleryIndexRoute
}
export interface FileRoutesByTo {
  '/confirm-email': typeof GuestConfirmEmailRoute
  '/login': typeof GuestLoginRoute
  '/register': typeof GuestRegisterRoute
  '/reset-password': typeof GuestResetPasswordRoute
  '/account': typeof PrivateAccountRoute
  '/cart': typeof PublicCartRoute
  '/': typeof PublicIndexRoute
  '/editor/$id': typeof PublicEditorIdRoute
  '/gallery/$id': typeof PublicGalleryIdRoute
  '/gallery': typeof PublicGalleryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_guest': typeof GuestRouteWithChildren
  '/_private': typeof PrivateRouteWithChildren
  '/_guest/confirm-email': typeof GuestConfirmEmailRoute
  '/_guest/login': typeof GuestLoginRoute
  '/_guest/register': typeof GuestRegisterRoute
  '/_guest/reset-password': typeof GuestResetPasswordRoute
  '/_private/account': typeof PrivateAccountRoute
  '/_public/cart': typeof PublicCartRoute
  '/_public/': typeof PublicIndexRoute
  '/_public/editor/$id': typeof PublicEditorIdRoute
  '/_public/gallery/$id': typeof PublicGalleryIdRoute
  '/_public/gallery/': typeof PublicGalleryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/confirm-email'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/account'
    | '/cart'
    | '/'
    | '/editor/$id'
    | '/gallery/$id'
    | '/gallery'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/confirm-email'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/account'
    | '/cart'
    | '/'
    | '/editor/$id'
    | '/gallery/$id'
    | '/gallery'
  id:
    | '__root__'
    | '/_guest'
    | '/_private'
    | '/_guest/confirm-email'
    | '/_guest/login'
    | '/_guest/register'
    | '/_guest/reset-password'
    | '/_private/account'
    | '/_public/cart'
    | '/_public/'
    | '/_public/editor/$id'
    | '/_public/gallery/$id'
    | '/_public/gallery/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  GuestRoute: typeof GuestRouteWithChildren
  PrivateRoute: typeof PrivateRouteWithChildren
  PublicCartRoute: typeof PublicCartRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicEditorIdRoute: typeof PublicEditorIdRoute
  PublicGalleryIdRoute: typeof PublicGalleryIdRoute
  PublicGalleryIndexRoute: typeof PublicGalleryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PrivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/cart': {
      id: '/_public/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof PublicCartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/account': {
      id: '/_private/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof PrivateAccountRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_guest/reset-password': {
      id: '/_guest/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof GuestResetPasswordRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/register': {
      id: '/_guest/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof GuestRegisterRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/login': {
      id: '/_guest/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestLoginRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/confirm-email': {
      id: '/_guest/confirm-email'
      path: '/confirm-email'
      fullPath: '/confirm-email'
      preLoaderRoute: typeof GuestConfirmEmailRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_public/gallery/': {
      id: '/_public/gallery/'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof PublicGalleryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/gallery/$id': {
      id: '/_public/gallery/$id'
      path: '/gallery/$id'
      fullPath: '/gallery/$id'
      preLoaderRoute: typeof PublicGalleryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/editor/$id': {
      id: '/_public/editor/$id'
      path: '/editor/$id'
      fullPath: '/editor/$id'
      preLoaderRoute: typeof PublicEditorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface GuestRouteChildren {
  GuestConfirmEmailRoute: typeof GuestConfirmEmailRoute
  GuestLoginRoute: typeof GuestLoginRoute
  GuestRegisterRoute: typeof GuestRegisterRoute
  GuestResetPasswordRoute: typeof GuestResetPasswordRoute
}

const GuestRouteChildren: GuestRouteChildren = {
  GuestConfirmEmailRoute: GuestConfirmEmailRoute,
  GuestLoginRoute: GuestLoginRoute,
  GuestRegisterRoute: GuestRegisterRoute,
  GuestResetPasswordRoute: GuestResetPasswordRoute,
}

const GuestRouteWithChildren = GuestRoute._addFileChildren(GuestRouteChildren)

interface PrivateRouteChildren {
  PrivateAccountRoute: typeof PrivateAccountRoute
}

const PrivateRouteChildren: PrivateRouteChildren = {
  PrivateAccountRoute: PrivateAccountRoute,
}

const PrivateRouteWithChildren =
  PrivateRoute._addFileChildren(PrivateRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  GuestRoute: GuestRouteWithChildren,
  PrivateRoute: PrivateRouteWithChildren,
  PublicCartRoute: PublicCartRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicEditorIdRoute: PublicEditorIdRoute,
  PublicGalleryIdRoute: PublicGalleryIdRoute,
  PublicGalleryIndexRoute: PublicGalleryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
