name: Continuous Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"

      - name: Install packages
        run: npm ci

      - name: Update Wrangler configs
        run: sed -i "s/:local/:production/" wrangler.jsonc

      - name: Build source code
        run: npm run build:prod
        env:
          VITE_API_URL: ${{ secrets.PRODUCTION_API_URL }}
          VITE_API_VERSION: ${{ secrets.PRODUCTION_API_VERSION }}
          VITE_STRIPE_PUBLISHABLE_KEY: ${{ secrets.PRODUCTION_STRIPE_PUBLISHABLE_KEY }}

      - name: Deploy via Wrangler
        run: npm run deploy
